### ISSUE TITLE
Whataboutism causes javascript errors

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#1056]
End of https://studio.boardgamearena.com/1/innovationdev?table=473755

```caught TypeError: Cannot read properties of null (reading 'style')
    at i.set (dojo.js:1:53438)
    at e.style (dojo.js:1:70652)
    at innovationdev.addToZone (innovationdev.js?1683066095830:2894:14)
    at innovationdev.moveBetweenZones (innovationdev.js?1683066095830:2883:18)
    at innovationdev.notif_transferedCard (innovationdev.js?1683066095830:4440:18)
    at r.<anonymous> (dojo.js:1:23207)
    at r.i [as ontransferedCard] (dojo.js:1:43133)
    at o.emit (dojo.js:1:39135)
    at o.emit (dojo.js:1:39762)
    at r.emit (dojo.js:1:42740)```

**Comment by micahstairs** [comment]
I suspect the card order bug fixed this. But if it happens again, please file another issue!
