### ISSUE TITLE
Black Market leads to JS errors when the revealed achievements are returned

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1125]
Javascript error:
During notification transferedCard
Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')
at i.set (https://studio.boardgamearena.com:8084/data/themereleases/230620-1000/js/dojoroot/dojo/dojo.js:1:53438)
at e.style (https://studio.boardgamearena.com:8084/data/themereleases/230620-1000/js/dojoroot/dojo/dojo.js:1:70652)
at innovationkahlia.addToZone (https://studio.boardgamearena.com:8084/data/themereleases/current/games/innovationkahlia/999999-9999/innovationkahlia.js?1687575830316:2951:14)
at

**Comment by micahstairs** [comment]
It seems that only the opponents see the error, not the player using the card.

**Comment by micahstairs** [comment]
And it actually happens when the achievement is revealed.

**Comment by micahstairs** [comment]
Oh this happened because of `$message_for_others = clienttranslate('${player_name} reveal a ${<}${age}${>} to the available achievements.');`

Without `{<}${age}${>} ${<<}${name}${>>}`, the info about the card isn't passed to the front-end and then it's not possible to render it.
