### ISSUE TITLE
[Ultimate Dev] Argument 1 passed to Innovation\Cards\Card::__construct() must be an instance of Innovation

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#1134]
In the game https://studio.boardgamearena.com/table?table=499160, trying to dogma Polytheism, Chartreuse, Pantheism, Counterintelligence, Fortune Cookie, Black Market, Safe Deposit Box, Camouflage, Mafia, Private Eye, Slot Machine, Subway, Pilot Voucher, Pilgrimage, or Writing(!) resulted in the following error (or a slight variant thereof): 
```
Server syntax error:
Fatal error: Uncaught TypeError: Argument 1 passed to Innovation\Cards\Card::__construct() must be an instance of Innovation, instance of innovationdev given, called in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 11388 and defined in /var/tournoi/release/games/innovationdev/999999-9999/modules/Innovation/Cards/Card.php:16 Stack trace: #0 /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php(11388): Innovation\Cards\Card->__construct() #1 /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php(11470): innovationdev->getCardInstance() #2 /var/tournoi/release/tournoi-230628-1001-gs/www/game/module/table/gamestate.game.php(502): innovationdev->stPlayerInvolvedTurn() #3 /var/tournoi/release/tournoi-230628-1001-gs/www/game/module/table/gamestate.game.php(398): Gamestate->jumpToState() #4 /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php(11138): Gamestate->nextState() #5 /var/tournoi/release/tournoi-230628-1001-gs/www/game in /var/tournoi/release/games/innovationdev/999999-9999/modules/Innovation/Cards/Card.php on line 16
```

Trying to reproduce that error in another game failed; see https://studio.boardgamearena.com/table?table=498160.

**Comment by micahstairs** [comment]
Fixed! Let me know if you still see it.
