### ISSUE TITLE
Fix EndOfGame error

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1177]
[Mon Jul 10 17:28:01.480799 2023] [php7:error] [pid 2204716:tid [client 24.218.21.8, 136.226.18.54] PHP Fatal error:  Uncaught EndOfGame in /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php:5113\nStack trace:\n#0 /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php(1974): innovationalpha->incrementBGAScore()\n#1 /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php(1557): innovationalpha->updateGameSituation()\n#2 /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php(3316): innovationalpha->transferCardFromTo()\n#3 /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php(3149): innovationalpha->checkForSpecialAchievementsForPlayer()\n#4 /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php(1990): innovationalpha->checkForSpecialAchievements()\n#5 /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php(1557): innovationalpha->updateGameSituation()\n#6 /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php(1323): innovationalpha->t in /var/tournoi/release/games/innovationalpha/230709-1601/innovationalpha.game.php on line 5113, referer https://boardgamearena.com/2/innovationalpha?table=393921478

**Comment by micahstairs** [comment]
I haven't seen the error appear in a little while. We can keep an eye on the innovationalpha logs to see if it happens again.
