### ISSUE TITLE
Scissors first effect returns an error

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1228]
Javascript error:
During notification gameStateChange
string.substitute could not find key "card" in template
Error: string.substitute could not find key "card" in template
at https://studio.boardgamearena.com:8084/data/themereleases/230719-1002/js/modules/layer/ly_studio.js:1:52786
at String.replace ()
at o.substitute (https://studio.boardgamearena.com:8084/data/themereleases/230719-1002/js/modules/layer/ly_studio.js:1:52603)
at Innovation.onUpdateActionButtons (https://studio.boardgamearena.com:8084/data/themereleases/current/games/innovation/999999-9999/innovation.js?1689908916880:1392:88)
at Object.updatePageTitle (https://studio.boardgamearena.com:8084/data/themereleases/230719-1002/js/modules/layer/ly_studio.js:1:546279)

**Comment by micahstairs** [comment]
Did you force refresh your JS?
