### ISSUE TITLE
Relic Seize is not working

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#248]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

I see two issues.  First, this happens if you try to seize a relic to hand:

![image](https://user-images.githubusercontent.com/11416698/154336308-33867e4b-47b1-4f46-be99-865671e5ea0e.png)

Second, this error occurs if you try seize to the achievement pile:

Javascript error:
During notification transferedCard
Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')
at Object.i.set (https://studio.boardgamearena.com:8084/data/themereleases/220215-1000/js/dojoroot/dojo/dojo.js:1:53351)
at Object.e.style (https://studio.boardgamearena.com:8084/data/themereleases/220215-1000/js/dojoroot/dojo/dojo.js:1:70522)
at Object.addToZone (https://studio.boardgamearena.com:8084/data/themereleases/current/games/innovationkahlia/999999-9999/innovationkahlia.js?1645037259831:2091:18)
at Object.moveBetweenZones (https://studio.boardgamearena.com:8084/data/themereleases/current/games/innovationkahlia/999999-9999/innovationkahlia.js?1645037259831:2081:22)
at Object.notif_transferedCard (https://studio.boardgamearena.com:8084/data/themereleases/current/games/innovationkahlia/999999-9999/innovationkahlia.js?1645037259831:3230:18)
at r.

**Comment by micahstairs** [comment]
Thanks for filing this! I can take it on.

I should note that the relic error you are seeing will only happen when seizing from another player's achievement pile to your hand. That will be easy to fix.

The other part of this bug will require a deeper investigation!
