### ISSUE TITLE
replay leads to JS errors

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#347]
Javascript error:
During notification gameStateChange
Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')
at c (https://studio.boardgamearena.com:8084/data/themereleases/220322-1000/js/dojoroot/dojo/dojo.js:1:52644)
at Object.i.set (https://studio.boardgamearena.com:8084/data/themereleases/220322-1000/js/dojoroot/dojo/dojo.js:1:53342)
at Object.e.style (https://studio.boardgamearena.com:8084/data/themereleases/220322-1000/js/dojoroot/dojo/dojo.js:1:70522)
at Object.show (https://studio.boardgamearena.com:8084/data/themereleases/220322-1000/js/modules/layer/ly_studio.js:1:460714)
at Object.show (https://studio.boardgamearena.com:8084/data/themereleases/220322-1000/js/modules/layer/ly_studio.js:1:322102)
at Object.onEnteringState (https://studio.boardgamearena.com:8084/data/themereleases/current/games/innovationdev/999999-9999/innovationdev.js?1649018683787:881:60)
at Object.ntf_gameStateChange (https://studio.boardgamearena.com:8084/data/themereleases/220322-1000/js/modules/layer/ly_studio.js:1:636951)

**Comment by micahstairs** [comment]
@ultimatefiend Can you provide me more details on how to replicate this error?

**Comment by ultimatefiend** [comment]
Sorry I don't.  I will watch more replays and see if it happens again.  Everything just flies by during the replay.

I was hoping the log that I grabbed would be sufficient.

**Comment by micahstairs** [comment]
Your original post said "le to kahliadev0's score pile", so maybe I'll try a replay which includes a transfer to a score pile.

**Comment by ultimatefiend** [comment]
All of my replays appear to be messed up and people have stopped taking turns so it might be a bit before I have more replays to look at.

**Comment by ultimatefiend** [comment]
I can't look at replays anymore so this might not be an issue.  Maybe an alpha replay could shed some light?

**Comment by micahstairs** [comment]
I suggest we just close this. And if we see problems again, we can file a new issue with actionable steps to fix it.

**Comment by micahstairs** [comment]
FYI This problem surfaced again in https://github.com/micahstairs/bga-innovation/issues/622 and I found a fix!
