### ISSUE TITLE
Replays do not always work correctly

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#49]
When an Innovation game is replayed, it doesn't always work correctly.

*  https://boardgamearena.com/bug?id=8858: Cards leaving the score pile don't seem to actually move.
*  https://boardgamearena.com/bug?id=18582: Fission doesn't actually move cards when they are supposed to be returned.
*  https://boardgamearena.com/bug?id=25058: Cards don't get re-ordered using Publications.

In general, the above theme is that during replay, cards don't always move locations like they are supposed to.

**Comment by micahstairs** [comment]
I easily replicated the Fission bug. I found the following error in the console:

<img width="686" alt="Screen Shot 2021-12-27 at 2 57 56 PM" src="https://user-images.githubusercontent.com/7231485/147499870-4ab1150d-fe39-4239-b713-cf8ad2bc9933.png">

**Comment by micahstairs** [comment]
The problem might be related to the fact that after the first move in the replay, it's no longer possible to open the "(click to look at the cards)" score card popup with this error:

```
Javascript error:
During callback: onclick / clic_display_score_window
Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')
at c (https://studio.boardgamearena.com:8084/data/themereleases/211223-1100/js/dojoroot/dojo/dojo.js:1:52633)
at Object.i.set (https://studio.boardgamearena.com:8084/data/themereleases/211223-1100/js/dojoroot/dojo/dojo.js:1:53331)
at Object.e.style (https://studio.boardgamearena.com:8084/data/themereleases/211223-1100/js/dojoroot/dojo/dojo.js:1:70511)
at Object.show (https://studio.boardgamearena.com:8084/data/themereleases/211223-1100/js/modules/layer/ly_studio.js:1:458964)
at Object.show (https://studio.boardgamearena.com:8084/data/themereleases/211223-1100/js/modules/layer/ly_studio.js:1:322102)
at Object.clic_display_score_window (https://studio.boardgamearena.com:8084/data/themereleases/current/games/innovation/999999-9999/innovation.js?1640696725346:2910:40)
at Object. (https://studio.boardgamearena.com/archive/replay/211223-1100/?table=331397&player=2356652&comments=2356652;:2110:50)
at HTMLParagraphElement. (https://studio.boardgamearena.com:8084/data/themereleases/211223-1100/js/dojoroot/dojo/dojo.js:1:23201)
Script:
Url: https://studio.boardgamearena.com/archive/replay/211223-1100/?table=331397&player=2356652&comments=2356652;#
BGA version 211223-1100
U=2356652
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
```

**Comment by micahstairs** [comment]
I found a fix! I'll leave this issue open until we actually deploy the fix to production (which may be at the same time as we release the expansion).

**Comment by micahstairs** [comment]
This was deployed a few weeks ago.
